from selenium.webdriver.common.by import By

AUTH_BUTTON = (By.XPATH, '//*[starts-with(@class, "responseHead-module-button")]')
EMAIL_INPUT = (By.NAME, 'email')
PASSWORD_INPUT = (By.NAME, 'password')
AUTH_ACCEPT_BUTTON = (By.XPATH, '//*[starts-with(@class, "authForm-module-button")]')
USER_NAME_WRAP = (By.XPATH, '//*[starts-with(@class, "right-module-userNameWrap")]')
AUTH_WRONG_LOGIN = (By.XPATH, '//*[starts-with(@class, "notify-module-wrapper")]')
RIGHT_USER_MENU = (By.XPATH, '//*[starts-with(@class, "right-module-rightButton")]')
RIGHT_MENU_LOGOUT = (By.XPATH, '//*[starts-with(@class, "rightMenu-module-rightMenu")]/li[2]')
CENTER_MENU_PROFILE = (By.XPATH, '//a[contains(@class, "center-module-profile")]')
MAIN_PAGE = (By.XPATH, '//*[starts-with(@class, "instruction-module-wrapper")]')
FIO_PROFILE_INPUT = (By.XPATH, '//input[@maxlength="100"]')
INN_PROFILE_INPUT = (By.XPATH, '//input[@maxlength="12"]')
PROFILE_ACCEPT_BUTTON = (By.CSS_SELECTOR, '.button_submit')
SUCCESS_NOTIFY = (By.XPATH, '//*[contains(@class, "js-group-form-success-bg")]')
CENTER_MENU_STATISTICS = (By.XPATH, '//a[contains(@class, "center-module-statistics")]')
STATISTICS_PAGE = (By.XPATH, '//*[contains(@class, "ads-summary-statistics__tab-content")]')
PROFILE_PAGE = (By.XPATH, '//*[@class="profile-contact-info"]')
